(defun color-theme-brandon ()
  "Color theme by brandon, created 2004-08-12."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "white")
      (background-mode . light)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "#000000000000")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cursor-color . "Red3")
      (foreground-color . "black")
      (mouse-color . "black")
      (senator-eldoc-use-color . t)
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (vc-annotate-very-old-color . "#0046FF")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "black")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (display-time-mail-face . mode-line)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (hl-line-face . highlight)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (rmail-highlight-face . font-lock-function-name-face)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :family "outline-courier new"))))
     (Buffer-menu-buffer-face ((t (nil))))
     (CUA-global-mark-face ((t (nil))))
     (CUA-rectangle-face ((t (nil))))
     (CUA-rectangle-noselect-face ((t (nil))))
     (Info-title-1-face ((t (nil))))
     (Info-title-2-face ((t (nil))))
     (Info-title-3-face ((t (nil))))
     (Info-title-4-face ((t (nil))))
     (antlr-font-lock-keyword-face ((t (nil))))
     (antlr-font-lock-literal-face ((t (nil))))
     (antlr-font-lock-ruledef-face ((t (nil))))
     (antlr-font-lock-ruleref-face ((t (nil))))
     (antlr-font-lock-tokendef-face ((t (nil))))
     (antlr-font-lock-tokenref-face ((t (nil))))
     (bbdb-company ((t (nil))))
     (bbdb-field-name ((t (nil))))
     (bbdb-field-value ((t (nil))))
     (bbdb-name ((t (nil))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (blank-space-face ((t (nil))))
     (blank-tab-face ((t (nil))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "#000000000000"))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (nil))))
     (button ((t (:bold t :weight bold))))
     (calendar-today-face ((t (nil))))
     (change-log-acknowledgement-face ((t (nil))))
     (change-log-conditionals-face ((t (nil))))
     (change-log-date-face ((t (nil))))
     (change-log-email-face ((t (nil))))
     (change-log-file-face ((t (nil))))
     (change-log-function-face ((t (nil))))
     (change-log-list-face ((t (nil))))
     (change-log-name-face ((t (nil))))
     (clearcase-dired-checkedout-face ((t (nil))))
     (cmode-bracket-face ((t (:bold t :weight bold))))
     (comint-highlight-input ((t (nil))))
     (comint-highlight-prompt ((t (nil))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (completions-common-part ((t (:family "outline-courier new" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 98))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cparen-around-andor-face ((t (nil))))
     (cparen-around-begin-face ((t (nil))))
     (cparen-around-conditional-face ((t (nil))))
     (cparen-around-define-face ((t (nil))))
     (cparen-around-lambda-face ((t (nil))))
     (cparen-around-letdo-face ((t (nil))))
     (cparen-around-quote-face ((t (nil))))
     (cparen-around-set!-face ((t (nil))))
     (cparen-around-syntax-rules-face ((t (nil))))
     (cparen-around-vector-face ((t (nil))))
     (cparen-binding-face ((t (nil))))
     (cparen-binding-list-face ((t (nil))))
     (cparen-conditional-clause-face ((t (nil))))
     (cparen-normal-paren-face ((t (nil))))
     (cperl-array-face ((t (nil))))
     (cperl-hash-face ((t (nil))))
     (cperl-here-face ((t (nil))))
     (cperl-invalid-face ((t (nil))))
     (cperl-nonoverridable-face ((t (nil))))
     (cperl-pod-face ((t (nil))))
     (cperl-pod-head-face ((t (nil))))
     (cua-global-mark-face ((t (:background "yellow" :foreground "black"))))
     (cua-rectangle-face ((t (nil))))
     (cua-rectangle-noselect-face ((t (nil))))
     (cursor ((t (:background "Red3" :foreground "black"))))
     (custom-button-face ((t (:bold t :foreground "#999" :weight bold))))
     (custom-button-pressed-face ((t (nil))))
     (custom-changed-face ((t (nil))))
     (custom-comment-face ((t (nil))))
     (custom-comment-tag-face ((t (nil))))
     (custom-documentation-face ((t (nil))))
     (custom-face-tag-face ((t (nil))))
     (custom-group-tag-face ((t (nil))))
     (custom-group-tag-face-1 ((t (nil))))
     (custom-invalid-face ((t (nil))))
     (custom-modified-face ((t (nil))))
     (custom-rogue-face ((t (nil))))
     (custom-saved-face ((t (nil))))
     (custom-set-face ((t (nil))))
     (custom-state-face ((t (nil))))
     (custom-variable-button-face ((t (nil))))
     (custom-variable-tag-face ((t (nil))))
     (cvs-filename-face ((t (nil))))
     (cvs-handled-face ((t (nil))))
     (cvs-header-face ((t (nil))))
     (cvs-marked-face ((t (nil))))
     (cvs-msg-face ((t (nil))))
     (cvs-need-action-face ((t (nil))))
     (cvs-unknown-face ((t (nil))))
     (cyan ((t (nil))))
     (diary-face ((t (nil))))
     (diff-added-face ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context-face ((t (nil))))
     (diff-file-header-face ((t (nil))))
     (diff-function-face ((t (nil))))
     (diff-header-face ((t (nil))))
     (diff-hunk-header-face ((t (nil))))
     (diff-index-face ((t (nil))))
     (diff-nonexistent-face ((t (nil))))
     (diff-removed-face ((t (nil))))
     (dired-face-boring ((t (nil))))
     (dired-face-directory ((t (nil))))
     (dired-face-executable ((t (nil))))
     (dired-face-flagged ((t (nil))))
     (dired-face-header ((t (nil))))
     (dired-face-marked ((t (nil))))
     (dired-face-permissions ((t (nil))))
     (dired-face-setuid ((t (nil))))
     (dired-face-socket ((t (nil))))
     (dired-face-symlink ((t (nil))))
     (display-time-mail-balloon-enhance-face ((t (nil))))
     (display-time-mail-balloon-gnus-group-face ((t (nil))))
     (display-time-time-balloon-face ((t (nil))))
     (ebrowse-default-face ((t (nil))))
     (ebrowse-file-name-face ((t (nil))))
     (ebrowse-member-attribute-face ((t (nil))))
     (ebrowse-member-class-face ((t (nil))))
     (ebrowse-progress-face ((t (nil))))
     (ebrowse-root-class-face ((t (nil))))
     (ebrowse-tree-mark-face ((t (nil))))
     (ecb-bucket-token-face ((t (:bold t :weight bold))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:background "magenta" :height 1.0))))
     (ecb-directories-general-face ((t (:height 0.9))))
     (ecb-directory-face ((t (:background "Cyan4"))))
     (ecb-history-face ((t (:background "Cyan4"))))
     (ecb-history-general-face ((t (:height 0.9))))
     (ecb-method-face ((t (:background "Cyan4" :slant normal :weight normal))))
     (ecb-methods-general-face ((t (:slant normal))))
     (ecb-source-face ((t (:background "Cyan4"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-face ((t (nil))))
     (ecb-sources-general-face ((t (:height 0.9))))
     (ecb-token-header-face ((t (:background "Steelblue4"))))
     (ecb-type-token-class-face ((t (:bold t :weight bold))))
     (ecb-type-token-enum-face ((t (:bold t :weight bold))))
     (ecb-type-token-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-token-interface-face ((t (:bold t :weight bold))))
     (ecb-type-token-struct-face ((t (:bold t :weight bold))))
     (ecb-type-token-typedef-face ((t (:bold t :weight bold))))
     (edb-inter-field-face ((t (nil))))
     (edb-normal-summary-face ((t (nil))))
     (ediff-current-diff-face-A ((t (nil))))
     (ediff-current-diff-face-Ancestor ((t (nil))))
     (ediff-current-diff-face-B ((t (nil))))
     (ediff-current-diff-face-C ((t (nil))))
     (ediff-even-diff-face-A ((t (nil))))
     (ediff-even-diff-face-Ancestor ((t (nil))))
     (ediff-even-diff-face-B ((t (nil))))
     (ediff-even-diff-face-C ((t (nil))))
     (ediff-fine-diff-face-A ((t (nil))))
     (ediff-fine-diff-face-Ancestor ((t (nil))))
     (ediff-fine-diff-face-B ((t (nil))))
     (ediff-fine-diff-face-C ((t (nil))))
     (ediff-odd-diff-face-A ((t (nil))))
     (ediff-odd-diff-face-Ancestor ((t (nil))))
     (ediff-odd-diff-face-B ((t (nil))))
     (ediff-odd-diff-face-C ((t (nil))))
     (eieio-custom-slot-tag-face ((t (nil))))
     (emacs-wiki-bad-link-face ((t (nil))))
     (emacs-wiki-link-face ((t (nil))))
     (erc-action-face ((t (nil))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :weight bold))))
     (erc-dangerous-host-face ((t (nil))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (nil))))
     (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-fool-face ((t (nil))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (:foreground "#555"))))
     (erc-inverse-face ((t (:background "steel blue"))))
     (erc-keyword-face ((t (:bold t :foreground "#999" :weight bold))))
     (erc-nick-default-face ((t (nil))))
     (erc-nick-msg-face ((t (:foreground "#888"))))
     (erc-notice-face ((t (:foreground "#444"))))
     (erc-pal-face ((t (:foreground "#888"))))
     (erc-prompt-face ((t (:bold t :foreground "#777" :weight bold))))
     (erc-timestamp-face ((t (:bold t :foreground "#777" :weight bold))))
     (erc-underline-face ((t (nil))))
     (eshell-ls-archive-face ((t (nil))))
     (eshell-ls-backup-face ((t (nil))))
     (eshell-ls-clutter-face ((t (nil))))
     (eshell-ls-directory-face ((t (nil))))
     (eshell-ls-executable-face ((t (nil))))
     (eshell-ls-missing-face ((t (nil))))
     (eshell-ls-picture-face ((t (nil))))
     (eshell-ls-product-face ((t (nil))))
     (eshell-ls-readonly-face ((t (nil))))
     (eshell-ls-special-face ((t (nil))))
     (eshell-ls-symlink-face ((t (nil))))
     (eshell-ls-text-face ((t (nil))))
     (eshell-ls-todo-face ((t (nil))))
     (eshell-ls-unreadable-face ((t (nil))))
     (eshell-prompt-face ((t (nil))))
     (eshell-test-failed-face ((t (nil))))
     (eshell-test-ok-face ((t (nil))))
     (excerpt ((t (:italic t :slant italic))))
     (extra-whitespace-face ((t (nil))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (fg:black ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (nil))))
     (fl-comment-face ((t (nil))))
     (fl-doc-string-face ((t (nil))))
     (fl-function-name-face ((t (nil))))
     (fl-keyword-face ((t (nil))))
     (fl-string-face ((t (nil))))
     (fl-type-face ((t (nil))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (flyspell-duplicate-face ((t (nil))))
     (flyspell-incorrect-face ((t (nil))))
     (font-latex-bold-face ((t (nil))))
     (font-latex-italic-face ((t (nil))))
     (font-latex-math-face ((t (nil))))
     (font-latex-sedate-face ((t (nil))))
     (font-latex-string-face ((t (nil))))
     (font-latex-warning-face ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "red3"))))
     (font-lock-comment-face ((t (:italic t :slant italic :foreground "orange"))))
     (font-lock-constant-face ((t (:foreground "red3"))))
     (font-lock-doc-face ((t (:foreground "#777"))))
     (font-lock-doc-string-face ((t (:foreground "darkgreen"))))
     (font-lock-emphasized-face ((t (:bold t :weight bold))))
     (font-lock-exit-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:bold t :foreground "red" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "steelblue" :weight bold))))
     (font-lock-other-emphasized-face ((t (nil))))
     (font-lock-other-type-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "blue3"))))
     (font-lock-reference-face ((t (:foreground "red3"))))
     (font-lock-special-comment-face ((t (nil))))
     (font-lock-special-keyword-face ((t (nil))))
     (font-lock-string-face ((t (:foreground "green4"))))
     (font-lock-type-face ((t (:bold t :foreground "blue" :weight bold))))
     (font-lock-variable-name-face ((t (:foreground "black"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (fringe ((t (:background "#111" :foreground "#444"))))
     (gdb-arrow-face ((t (:bold t :background "LightGreen" :foreground "black" :weight bold))))
     (gnus-cite-attribution-face ((t (:foreground "#bbb"))))
     (gnus-cite-face-1 ((t (:foreground "#aaa"))))
     (gnus-cite-face-10 ((t (nil))))
     (gnus-cite-face-11 ((t (nil))))
     (gnus-cite-face-2 ((t (:foreground "#aaa"))))
     (gnus-cite-face-3 ((t (:foreground "#aaa"))))
     (gnus-cite-face-4 ((t (:foreground "#aaa"))))
     (gnus-cite-face-5 ((t (:foreground "#aaa"))))
     (gnus-cite-face-6 ((t (:foreground "#aaa"))))
     (gnus-cite-face-7 ((t (:foreground "#aaa"))))
     (gnus-cite-face-8 ((t (:foreground "#aaa"))))
     (gnus-cite-face-9 ((t (:foreground "#aaa"))))
     (gnus-cite-face-list ((t (:bold t :foreground "red" :weight bold))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:foreground "#ccc"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:foreground "#999"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "#999" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "#999"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "#999" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "#888"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "#888" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "#777"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "#777" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "#999"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "#999" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "#888"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "#888" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "#777"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "#777" :weight bold))))
     (gnus-group-news-4-empty-face ((t (:foreground "#666"))))
     (gnus-group-news-4-face ((t (:bold t :foreground "#666" :weight bold))))
     (gnus-group-news-5-empty-face ((t (:foreground "#666"))))
     (gnus-group-news-5-face ((t (:bold t :foreground "#666" :weight bold))))
     (gnus-group-news-6-empty-face ((t (:foreground "#666"))))
     (gnus-group-news-6-face ((t (:bold t :foreground "#666" :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "#666"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "#666" :weight bold))))
     (gnus-header-content-face ((t (:foreground "#888"))))
     (gnus-header-from-face ((t (:bold t :foreground "#888" :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "#777" :weight bold))))
     (gnus-header-newsgroups-face ((t (:bold t :foreground "#777" :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "#999" :weight bold))))
     (gnus-picon-face ((t (nil))))
     (gnus-picon-xbm-face ((t (nil))))
     (gnus-picons-face ((t (nil))))
     (gnus-picons-xbm-face ((t (nil))))
     (gnus-server-agent-face ((t (nil))))
     (gnus-server-closed-face ((t (nil))))
     (gnus-server-denied-face ((t (nil))))
     (gnus-server-offline-face ((t (nil))))
     (gnus-server-opened-face ((t (nil))))
     (gnus-signature-face ((t (:foreground "#444"))))
     (gnus-splash ((t (nil))))
     (gnus-splash-face ((t (:foreground "#ccc"))))
     (gnus-summary-cancelled-face ((t (:background "#555" :foreground "#000"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "#555" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "#666" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "#777" :weight bold))))
     (gnus-summary-high-undownloaded-face ((t (nil))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "#888" :weight bold))))
     (gnus-summary-low-ancient-face ((t (:foreground "#444"))))
     (gnus-summary-low-read-face ((t (:foreground "#555"))))
     (gnus-summary-low-ticked-face ((t (:foreground "#666"))))
     (gnus-summary-low-undownloaded-face ((t (nil))))
     (gnus-summary-low-unread-face ((t (:foreground "#777"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "#555"))))
     (gnus-summary-normal-read-face ((t (:foreground "#666"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "#777"))))
     (gnus-summary-normal-undownloaded-face ((t (nil))))
     (gnus-summary-normal-unread-face ((t (:foreground "#888"))))
     (gnus-summary-selected-face ((t (:background "#333"))))
     (gnus-x-face ((t (nil))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (nil))))
     (gui-element ((t (nil))))
     (header-line ((t (:background "#333" :foreground "#000"))))
     (help-argument-name ((t (:bold t :weight bold))))
     (hi-black-b ((t (nil))))
     (hi-black-hb ((t (nil))))
     (hi-blue ((t (nil))))
     (hi-blue-b ((t (nil))))
     (hi-green ((t (nil))))
     (hi-green-b ((t (nil))))
     (hi-pink ((t (nil))))
     (hi-red-b ((t (nil))))
     (hi-yellow ((t (nil))))
     (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
     (highlight-changes-delete-face ((t (nil))))
     (highlight-changes-face ((t (nil))))
     (highline-face ((t (nil))))
     (highline-vertical-face ((t (:background "lightcyan"))))
     (holiday-face ((t (:background "#000" :foreground "#777"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (hproperty:but-face ((t (:bold t :background "wheat" :foreground "medium violet red" :weight bold))))
     (hproperty:flash-face ((t (:bold t :background "wheat" :foreground "gray80" :weight bold))))
     (hproperty:highlight-face ((t (:bold t :background "wheat" :foreground "red" :weight bold))))
     (hproperty:item-face ((t (:bold t :weight bold))))
     (html-helper-bold-face ((t (nil))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (nil))))
     (html-helper-italic-face ((t (nil))))
     (html-helper-underline-face ((t (nil))))
     (html-tag-face ((t (nil))))
     (hyper-apropos-documentation ((t (nil))))
     (hyper-apropos-heading ((t (nil))))
     (hyper-apropos-hyperlink ((t (nil))))
     (hyper-apropos-major-heading ((t (nil))))
     (hyper-apropos-section-heading ((t (nil))))
     (hyper-apropos-warning ((t (nil))))
     (ibuffer-deletion-face ((t (nil))))
     (ibuffer-marked-face ((t (nil))))
     (idlwave-help-link-face ((t (nil))))
     (idlwave-shell-bp-face ((t (nil))))
     (ido-first-match-face ((t (nil))))
     (ido-indicator-face ((t (nil))))
     (ido-only-match-face ((t (nil))))
     (ido-subdir-face ((t (nil))))
     (info-header-node ((t (:foreground "#666"))))
     (info-header-xref ((t (:foreground "#666"))))
     (info-menu-5 ((t (:underline t))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:bold t :foreground "#666" :weight bold))))
     (info-node ((t (:bold t :foreground "#888" :weight bold))))
     (info-xref ((t (:bold t :foreground "#777" :weight bold))))
     (isearch ((t (:background "red" :foreground "pink"))))
     (isearch-lazy-highlight-face ((t (:foreground "red"))))
     (isearch-secondary ((t (nil))))
     (ispell-face ((t (:bold t :weight bold))))
     (italic ((t (:bold t :weight bold))))
     (jde-bug-breakpoint-cursor ((t (nil))))
     (jde-bug-breakpoint-marker ((t (nil))))
     (jde-db-active-breakpoint-face ((t (nil))))
     (jde-db-requested-breakpoint-face ((t (nil))))
     (jde-db-spec-breakpoint-face ((t (nil))))
     (jde-java-font-lock-api-face ((t (nil))))
     (jde-java-font-lock-bold-face ((t (nil))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (nil))))
     (jde-java-font-lock-doc-tag-face ((t (nil))))
     (jde-java-font-lock-italic-face ((t (nil))))
     (jde-java-font-lock-link-face ((t (nil))))
     (jde-java-font-lock-modifier-face ((t (nil))))
     (jde-java-font-lock-number-face ((t (nil))))
     (jde-java-font-lock-operator-face ((t (nil))))
     (jde-java-font-lock-package-face ((t (nil))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (nil))))
     (lazy-highlight-face ((t (nil))))
     (left-margin ((t (nil))))
     (linemenu-face ((t (nil))))
     (list-mode-item-selected ((t (nil))))
     (log-view-file-face ((t (nil))))
     (log-view-message-face ((t (nil))))
     (magenta ((t (nil))))
     (makefile-space-face ((t (nil))))
     (man-bold ((t (nil))))
     (man-heading ((t (nil))))
     (man-italic ((t (nil))))
     (man-xref ((t (nil))))
     (menu ((t (:background "#111" :foreground "#444"))))
     (message-cited-text ((t (nil))))
     (message-cited-text-face ((t (:foreground "red"))))
     (message-header-cc-face ((t (:foreground "MidnightBlue"))))
     (message-header-contents ((t (nil))))
     (message-header-name-face ((t (:foreground "cornflower blue"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "blue4" :slant italic :weight bold))))
     (message-header-other-face ((t (:foreground "steel blue"))))
     (message-header-subject-face ((t (:bold t :foreground "navy blue" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "MidnightBlue" :weight bold))))
     (message-header-xheader-face ((t (:foreground "blue"))))
     (message-headers ((t (nil))))
     (message-highlighted-header-contents ((t (nil))))
     (message-mml-face ((t (:foreground "ForestGreen"))))
     (message-separator-face ((t (:foreground "brown"))))
     (message-url ((t (nil))))
     (minibuffer-prompt ((t (:foreground "555"))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (nil))))
     (mode-line ((t (:background "dimgray" :foreground "lemonchiffon"))))
     (mode-line-inactive ((t (:background "#000" :foreground "#444"))))
     (modeline-buffer-id ((t (:background "dimgray" :foreground "green3"))))
     (modeline-mousable ((t (:background "dimgray" :foreground "orange"))))
     (modeline-mousable-minor-mode ((t (:background "dimgray" :foreground "blue4"))))
     (mouse ((t (nil))))
     (mpg123-face-cur ((t (nil))))
     (mpg123-face-slider ((t (nil))))
     (my-summary-highlight-face ((t (:foreground "White"))))
     (my-tab-face ((t (nil))))
     (my-url-face ((t (:foreground "PaleTurquoise"))))
     (nil ((t (nil))))
     (overlay-empty-face ((t (nil))))
     (p4-depot-added-face ((t (:foreground "steelblue1"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey90"))))
     (p4-diff-change-face ((t (:foreground "dark green"))))
     (p4-diff-del-face ((t (nil))))
     (p4-diff-file-face ((t (:background "blue"))))
     (p4-diff-head-face ((t (:background "blue"))))
     (p4-diff-ins-face ((t (:foreground "steelblue1"))))
     (paren-blink-off ((t (nil))))
     (paren-face ((t (nil))))
     (paren-face-match ((t (nil))))
     (paren-face-mismatch ((t (nil))))
     (paren-face-no-match ((t (nil))))
     (paren-match ((t (nil))))
     (paren-mismatch ((t (nil))))
     (paren-mismatch-face ((t (nil))))
     (paren-no-match-face ((t (nil))))
     (pointer ((t (nil))))
     (primary-selection ((t (:background "gray65"))))
     (qt-classes-face ((t (:foreground "Red"))))
     (reb-match-0 ((t (nil))))
     (reb-match-1 ((t (nil))))
     (reb-match-2 ((t (nil))))
     (reb-match-3 ((t (nil))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "gray65"))))
     (right-margin ((t (nil))))
     (rpm-spec-dir-face ((t (nil))))
     (rpm-spec-doc-face ((t (nil))))
     (rpm-spec-ghost-face ((t (nil))))
     (rpm-spec-macro-face ((t (nil))))
     (rpm-spec-package-face ((t (nil))))
     (rpm-spec-tag-face ((t (nil))))
     (rpm-spec-var-face ((t (nil))))
     (scroll-bar ((t (nil))))
     (searchm-buffer ((t (:bold t :weight bold))))
     (searchm-button ((t (:bold t :weight bold))))
     (searchm-field ((t (nil))))
     (searchm-field-label ((t (:bold t :weight bold))))
     (searchm-highlight ((t (:bold t :weight bold))))
     (secondary-selection ((t (:background "paleturquoise"))))
     (semantic-dirty-token-face ((t (nil))))
     (semantic-intangible-face ((t (nil))))
     (semantic-read-only-face ((t (nil))))
     (semantic-unmatched-syntax-face ((t (nil))))
     (senator-intangible-face ((t (nil))))
     (senator-momentary-highlight-face ((t (nil))))
     (senator-read-only-face ((t (nil))))
     (setnu-line-number-face ((t (:bold t :background "Grey15" :foreground "White" :weight bold))))
     (sgml-comment-face ((t (nil))))
     (sgml-doctype-face ((t (nil))))
     (sgml-end-tag-face ((t (nil))))
     (sgml-entity-face ((t (nil))))
     (sgml-ignored-face ((t (nil))))
     (sgml-ms-end-face ((t (nil))))
     (sgml-ms-start-face ((t (nil))))
     (sgml-pi-face ((t (nil))))
     (sgml-sgml-face ((t (nil))))
     (sgml-short-ref-face ((t (nil))))
     (sgml-shortref-face ((t (nil))))
     (sgml-start-tag-face ((t (nil))))
     (sh-heredoc-face ((t (nil))))
     (shell-input-face ((t (:bold t :background "wheat" :foreground "blue" :weight bold))))
     (shell-option-face ((t (nil))))
     (shell-output-2-face ((t (nil))))
     (shell-output-3-face ((t (nil))))
     (shell-output-face ((t (nil))))
     (shell-prompt-face ((t (nil))))
     (show-block-face1 ((t (nil))))
     (show-block-face2 ((t (nil))))
     (show-block-face3 ((t (nil))))
     (show-block-face4 ((t (nil))))
     (show-block-face5 ((t (nil))))
     (show-block-face6 ((t (nil))))
     (show-block-face7 ((t (nil))))
     (show-block-face8 ((t (nil))))
     (show-block-face9 ((t (nil))))
     (show-paren-match-face ((t (:background "turquoise"))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (show-tabs-space-face ((t (nil))))
     (show-tabs-tab-face ((t (nil))))
     (show-trailing-whitespace ((t (:background "red" :foreground "blue"))))
     (smerge-base-face ((t (nil))))
     (smerge-markers-face ((t (nil))))
     (smerge-mine-face ((t (nil))))
     (smerge-other-face ((t (nil))))
     (speedbar-button-face ((t (nil))))
     (speedbar-directory-face ((t (nil))))
     (speedbar-file-face ((t (nil))))
     (speedbar-highlight-face ((t (nil))))
     (speedbar-selected-face ((t (nil))))
     (speedbar-separator-face ((t (nil))))
     (speedbar-tag-face ((t (nil))))
     (strokes-char-face ((t (nil))))
     (swbuff-current-buffer-face ((t (nil))))
     (tabbar-button-face ((t (nil))))
     (tabbar-default-face ((t (nil))))
     (tabbar-selected-face ((t (nil))))
     (tabbar-separator-face ((t (nil))))
     (tabbar-unselected-face ((t (nil))))
     (template-message-face ((t (nil))))
     (term-black ((t (nil))))
     (term-blackbg ((t (nil))))
     (term-blue ((t (nil))))
     (term-blue-bold-face ((t (nil))))
     (term-blue-face ((t (nil))))
     (term-blue-inv-face ((t (nil))))
     (term-blue-ul-face ((t (nil))))
     (term-bluebg ((t (nil))))
     (term-bold ((t (nil))))
     (term-cyan ((t (nil))))
     (term-cyan-bold-face ((t (nil))))
     (term-cyan-face ((t (nil))))
     (term-cyan-inv-face ((t (nil))))
     (term-cyan-ul-face ((t (nil))))
     (term-cyanbg ((t (nil))))
     (term-default ((t (nil))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-bold-face ((t (nil))))
     (term-default-face ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-default-inv-face ((t (nil))))
     (term-default-ul-face ((t (nil))))
     (term-green ((t (nil))))
     (term-green-bold-face ((t (nil))))
     (term-green-face ((t (nil))))
     (term-green-inv-face ((t (nil))))
     (term-green-ul-face ((t (nil))))
     (term-greenbg ((t (nil))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (nil))))
     (term-magenta-bold-face ((t (nil))))
     (term-magenta-face ((t (nil))))
     (term-magenta-inv-face ((t (nil))))
     (term-magenta-ul-face ((t (nil))))
     (term-magentabg ((t (nil))))
     (term-red ((t (nil))))
     (term-red-bold-face ((t (nil))))
     (term-red-face ((t (nil))))
     (term-red-inv-face ((t (nil))))
     (term-red-ul-face ((t (nil))))
     (term-redbg ((t (nil))))
     (term-underline ((t (nil))))
     (term-white ((t (nil))))
     (term-white-bold-face ((t (nil))))
     (term-white-face ((t (nil))))
     (term-white-inv-face ((t (nil))))
     (term-white-ul-face ((t (nil))))
     (term-whitebg ((t (nil))))
     (term-yellow ((t (nil))))
     (term-yellow-bold-face ((t (nil))))
     (term-yellow-face ((t (nil))))
     (term-yellow-inv-face ((t (nil))))
     (term-yellow-ul-face ((t (nil))))
     (term-yellowbg ((t (nil))))
     (tex-math-face ((t (nil))))
     (texinfo-heading-face ((t (nil))))
     (text-cursor ((t (:background "Red3" :foreground "white"))))
     (tool-bar ((t (:background "Gray80"))))
     (tooltip ((t (:background "#333" :foreground "#777"))))
     (trailing-whitespace ((t (nil))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (nil))))
     (vc-annotate-face-0046FF ((t (nil))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-divider ((t (:background "Gray80"))))
     (vhdl-font-lock-attribute-face ((t (nil))))
     (vhdl-font-lock-directive-face ((t (nil))))
     (vhdl-font-lock-enumvalue-face ((t (nil))))
     (vhdl-font-lock-function-face ((t (nil))))
     (vhdl-font-lock-generic-/constant-face ((t (nil))))
     (vhdl-font-lock-prompt-face ((t (nil))))
     (vhdl-font-lock-reserved-words-face ((t (nil))))
     (vhdl-font-lock-translate-off-face ((t (nil))))
     (vhdl-font-lock-type-face ((t (nil))))
     (vhdl-font-lock-variable-face ((t (nil))))
     (vhdl-speedbar-architecture-face ((t (nil))))
     (vhdl-speedbar-architecture-selected-face ((t (nil))))
     (vhdl-speedbar-configuration-face ((t (nil))))
     (vhdl-speedbar-configuration-selected-face ((t (nil))))
     (vhdl-speedbar-entity-face ((t (nil))))
     (vhdl-speedbar-entity-selected-face ((t (nil))))
     (vhdl-speedbar-instantiation-face ((t (nil))))
     (vhdl-speedbar-instantiation-selected-face ((t (nil))))
     (vhdl-speedbar-package-face ((t (nil))))
     (vhdl-speedbar-package-selected-face ((t (nil))))
     (vhdl-speedbar-subprogram-face ((t (nil))))
     (viper-minibuffer-emacs-face ((t (nil))))
     (viper-minibuffer-insert-face ((t (nil))))
     (viper-minibuffer-vi-face ((t (nil))))
     (viper-replace-overlay-face ((t (nil))))
     (viper-search-face ((t (nil))))
     (vm-header-content-face ((t (:italic t :foreground "gray80" :slant italic))))
     (vm-header-from-face ((t (:italic t :background "#65889C" :foreground "cyan" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-monochrome-image ((t (:background "white" :foreground "gray30"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (nil))))
     (vmpc-pre-sig-face ((t (nil))))
     (vmpc-sig-face ((t (nil))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (w3m-anchor-face ((t (nil))))
     (w3m-arrived-anchor-face ((t (nil))))
     (w3m-header-line-location-content-face ((t (nil))))
     (w3m-header-line-location-title-face ((t (nil))))
     (white ((t (nil))))
     (widget ((t (nil))))
     (widget-button-face ((t (:bold t :foreground "#888" :weight bold))))
     (widget-button-pressed-face ((t (nil))))
     (widget-documentation-face ((t (nil))))
     (widget-field-face ((t (:bold t :foreground "#999" :weight bold))))
     (widget-inactive-face ((t (nil))))
     (widget-single-line-field-face ((t (nil))))
     (woman-addition-face ((t (nil))))
     (woman-bold-face ((t (nil))))
     (woman-italic-face ((t (nil))))
     (woman-unknown-face ((t (nil))))
     (x-face ((t (nil))))
     (x-symbol-adobe-fontspecific-face ((t (nil))))
     (x-symbol-face ((t (nil))))
     (x-symbol-heading-face ((t (:bold t :weight bold))))
     (x-symbol-info-face ((t (nil))))
     (x-symbol-invisible-face ((t (nil))))
     (x-symbol-revealed-face ((t (nil))))
     (xrdb-option-name-face ((t (nil))))
     (xref-keyword-face ((t (:foreground "blue"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "navy"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xsl-fo-alternate-face ((t (:foreground "Yellow"))))
     (xsl-fo-main-face ((t (:foreground "PaleGreen"))))
     (xsl-other-element-face ((t (:foreground "Coral"))))
     (xsl-xslt-alternate-face ((t (:foreground "LightGray"))))
     (xsl-xslt-main-face ((t (:foreground "Wheat"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "gray65")))))))